server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Important for React Router (SPA) to serve index.html for all routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}
